spring.application.name=crack-the-number

spring.jpa.hibernate.ddl-auto=update

# giving access to hibernate on sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MYSQLDialect

# setting jdbc for efficient use for hibernate
spring.datasource.url=jdbc:mysql://localhost:3306/crackthenumber
spring.datasource.username=root
spring.datasource.password=skrillex
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
